"""UID table

Revision ID: 343c00bc5fbb
Revises: 
Create Date: 2021-06-09 22:15:54.818879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '343c00bc5fbb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ui_dtable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('UID', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ui_dtable_UID'), 'ui_dtable', ['UID'], unique=True)
    op.drop_table('test')
    op.drop_table('UIDtable')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('UIDtable',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('UID', sa.VARCHAR(length=20, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False)
    )
    op.create_table('test',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nom', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='PK__test__3213E83FD153B565')
    )
    op.drop_index(op.f('ix_ui_dtable_UID'), table_name='ui_dtable')
    op.drop_table('ui_dtable')
    # ### end Alembic commands ###
